# Generated by Django 5.0 on 2024-01-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('service_type', models.CharField(choices=[('W', 'Women Price'), ('M', 'Men Price'), ('K', 'Kids Price')], max_length=1)),
            ],
        ),
    ]
